### ISSUE TITLE
Multiple Tab Support

### ISSUE THREAD

**Issue by siddharth99** [gansm/finalcut#10]
Currently, I am running a very basic FApplication which has a number of FDialog's. However, I would like to build something that has multiple Tabs on the top and within each Tab a number of FDialog's. Please suggest a way to accomplish this.

Also, really appreciate the effort you have put in this library. I have found it useful for some of my use cases.

**Comment by gansm** [comment]
Unfortunately there is no FTab widget.

But with an FScrollView without visible scroll bars
```cpp
setVerticalScrollBarMode (fc::Hidden);
setHorizontalScrollBarMode (fc::Hidden);
```
you can easily move whole parts out of the visible area.
(Similar to a [css-sprite](https://css-tricks.com/css-sprites/))

Via FButtons (preferably without visible shadows) you could then use scrollToX() or scrollToY() to move parts of the dialog out of the visible area and back in again.

* https://codedocs.xyz/gansm/finalcut/classFScrollView.html
* https://codedocs.xyz/gansm/finalcut/classFButton.html

**Comment by siddharth99** [comment]
Thanks, I'll give FScrollView a try.

**Comment by siddharth99** [comment]
I looked at FScrollView and the example for the same; as far as I understand FScrollView is supposed to show different regions of the same widget. Since I want to show a completely different set of widgets on the new virtual tab FScrollView may not work. However, I found out that if I create a widget with multiple buttons on the top / left of the screen and attach each button to show / hide a particular set of widgets then I may be able to simulate behavior of tabs. Request you to please confirm my understanding.

**Comment by gansm** [comment]
FScrollView creates a scrollable virtual area.
In this area you can place widgets freely.

Here's a quick-and-dirty example that illustrates what I mean:
```cpp
#include <final/final.h>

struct MyScrollview : public FScrollView
{
  explicit MyScrollview (FWidget* parent = 0)
    : FScrollView(parent)
  {
    sw1 = new FSwitch(L"1st switch", this);
    sw1->setGeometry(14, 6, 14, 1);
    sw2 = new FSwitch(L"2nd switch", this);
    sw2->setGeometry(59, 6, 14, 1);
    sw2->setDisable();
  }

  ~MyScrollview()
  { }

  void draw()
  {
    setColor (wc.label_inactive_fg, wc.dialog_bg);
    clearArea();
    FScrollView::draw();
  }

  FSwitch* sw1;
  FSwitch* sw2;
};


struct ScrollExample : public FDialog
{
  explicit ScrollExample (FWidget* parent = 0)
    : FDialog(parent)
  {
    setGeometry (18, 4, 51, 19);
    setText("Tab simulation");

    // The scrolling viewport widget
    sview = new MyScrollview (this);
    sview->setGeometry(1, 1, 49, 13);
    sview->setScrollSize(92, 10);

    // comment out to show the scrollbar
    sview->setHorizontalScrollBarMode (fc::Hidden);

    FButton* first_button = new FButton("&1st", this);
    first_button->setGeometry(2, 15, 10, 1);
    first_button->setFocus();
    FButton* second_button = new FButton("&2nd", this);
    second_button->setGeometry(20, 15, 10, 1);
    FButton* quit_button = new FButton("&Quit", this);
    quit_button->setGeometry(38, 15, 10, 1);

    first_button->addCallback
    (
      "clicked",
      F_METHOD_CALLBACK (this, &ScrollExample::cb_first)
    );

    second_button->addCallback
    (
      "clicked",
      F_METHOD_CALLBACK (this, &ScrollExample::cb_second)
    );

    quit_button->addCallback
    (
      "clicked",
      F_METHOD_CALLBACK (this, &ScrollExample::cb_quit)
    );
  }

  ~ScrollExample()
  { }

  void onClose (FCloseEvent* ev)
  {  FApplication::closeConfirmationDialog (this, ev); }

  void cb_first (FCloseEvent*)
  {
    sview->scrollToX(1);
    sview->sw1->setEnable();
    sview->sw2->setDisable();
    sview->redraw();
  }

  void cb_second (FCloseEvent*)
  {
    sview->scrollToX(47);
    sview->sw1->setDisable();
    sview->sw2->setEnable();
    sview->redraw();
  }

  void cb_quit (FWidget*, data_ptr)
  { close(); }

  MyScrollview* sview;
};


int main (int argc, char* argv[])
{
  FApplication app(argc, argv);
  ScrollExample example(&app);
  app.setMainWidget(&example);
  example.show();
  return app.exec();
}
```
You can see the scrolling, if you comment the line with the "setHorizontalScrollBarMode".
