### ISSUE TITLE
is there some apps out there that uses final cut ?

### ISSUE THREAD

**Issue by alavaelian** [gansm/finalcut#101]
is there some apps made in final cut already i dont know just asking ?

**Comment by gansm** [comment]
FINAL CUT is mainly used in educational and private environments.

See [here](https://github.com/gansm/finalcut/issues/91#issuecomment-984568418) and [there](https://github.com/gansm/finalcut/issues/99#issuecomment-1012533295)

**Comment by alavaelian** [comment]
thas was very impresive work

**Comment by michael-lehn** [comment]
Maybe you could setup some _projects using final cut_ page and link to it from the main page of your project. Or some gallery with screenshots of programs based on final cut. I think currently you mostly get feedback when there is some feature request. But for most programmers the current state of final cut is just fine as it is.
