### ISSUE TITLE
an exception is displayed when the string starts with more than six consecutive zeros

### ISSUE THREAD

**Issue by kmnot** [gansm/finalcut#103]
```cpp
#include <final/final.h>

using namespace finalcut;

int main(int argc, char *argv[])
{
    FApplication app{argc, argv};
    FDialog dig{&app};
    FLineEdit lineedit{&dig}, lineedit2{&dig}, lineedit3{&dig};

    app.setMainWidget(&dig);

    dig.setSize(FSize{36, 12});

    lineedit.setGeometry(FPoint{3, 1}, FSize{dig.getDesktopWidth(), 1});
    lineedit2.setGeometry(FPoint{3, 3}, FSize{dig.getDesktopWidth(), 1});
    lineedit3.setGeometry(FPoint{3, 5}, FSize{dig.getDesktopWidth(), 1});

    lineedit.setText ("0000001");
    lineedit2.setText("00000001");
    lineedit3.setText("000000001");

    dig.show();

    return app.exec();
}
```

Hello, This is my code, and when I compile and execute it, it looks like this
![QQ截图20220513151106](https://user-images.githubusercontent.com/64987991/168231570-844d0607-ea10-4701-b741-8cb3bfd05e60.jpg)

lineedit2 and linedit3 are displayed abnormally

**Comment by gansm** [comment]
Hi kmnot, thanks for sharing your user experience. I have compiled and run your example. Everything looks as expected for me:

![image](https://user-images.githubusercontent.com/12223838/168271056-2ec4b0c1-87bf-4c63-ba4c-929ac4936391.png)


Now we need to find out why you have these display glitches. These glitches can be caused by the terminal font, for example, when a character is narrower than a terminal cell.

For better research, I need some information from your system environment:

* Which operating system do you use?
* Which distribution do you use?
* Which terminal do you use?
* Which font do you use and in which font size?
* What is the output of `echo $TERM` and `locale`?

By the way, you should use relative positioning in your code and use getClientWidth() instead of getDesktopWith().

See [widget layout](https://github.com/gansm/finalcut/wiki/First-steps#widget-layout)

Minor code improvement
```cpp
  auto rsw = std::size_t(1);  // Right shadow width
  lineedit.setGeometry(FPoint{1, 1}, FSize{dig.getClientWidth() - rsw, 1});
  lineedit2.setGeometry(FPoint{1, 3}, FSize{dig.getClientWidth() - rsw, 1});
  lineedit3.setGeometry(FPoint{1, 5}, FSize{dig.getClientWidth() - rsw, 1});
```

![image](https://user-images.githubusercontent.com/12223838/168271111-f7cf2053-9622-4c34-979b-8b4af01b5a65.png)

**Comment by kmnot** [comment]
> Hi kmnot, thanks for sharing your user experience. I have compiled and run your example. Everything looks as expected for me:
> 
> ![image](https://user-images.githubusercontent.com/12223838/168271056-2ec4b0c1-87bf-4c63-ba4c-929ac4936391.png)
> 
> Now we need to find out why you have these display glitches. These glitches can be caused by the terminal font, for example, when a character is narrower than a terminal cell.
> 
> For better research, I need some information from your system environment:
> 
> * Which operating system do you use?
> * Which distribution do you use?
> * Which terminal do you use?
> * Which font do you use and in which font size?
> * What is the output of `echo $TERM` and `locale`?
> 
> By the way, you should use relative positioning in your code and use getClientWidth() instead of getDesktopWith().
> 
> See [widget layout](https://github.com/gansm/finalcut/wiki/First-steps#widget-layout)
> 
> Minor code improvement
> 
> ```c++
>   auto rsw = std::size_t(1);  // Right shadow width
>   lineedit.setGeometry(FPoint{1, 1}, FSize{dig.getClientWidth() - rsw, 1});
>   lineedit2.setGeometry(FPoint{1, 3}, FSize{dig.getClientWidth() - rsw, 1});
>   lineedit3.setGeometry(FPoint{1, 5}, FSize{dig.getClientWidth() - rsw, 1});
> ```
> 
> ![image](https://user-images.githubusercontent.com/12223838/168271111-f7cf2053-9622-4c34-979b-8b4af01b5a65.png)

Thank you for your reply. At present, it can be determined that it is the problem of the analog terminal used by SecureCRT software. The xterm used by it will display exceptions (not sure which configuration is the problem), but the terminal used by vscode displays very normally

**Comment by gansm** [comment]
Now I'm curious about what's going on, and I also installed SecureCRT. But I did not have the display problems of your screenshot.

![image](https://user-images.githubusercontent.com/12223838/168443808-d3e84ad9-1ef3-4363-b894-cc20eaf750b6.png)

My terminal setting

![image](https://user-images.githubusercontent.com/12223838/168443820-784d6bce-901b-40ab-a9e4-1a40d764cd1c.png)
![image](https://user-images.githubusercontent.com/12223838/168443825-3b9829b3-a40b-4119-b700-2a74bc9053c8.png)

I have tested with RHEL7 and the SecureCRT version 9.2.1 (build 2768)

![image](https://user-images.githubusercontent.com/12223838/168443833-e216a856-fe68-42a4-b348-79972dd1f3ff.png)

**Comment by kmnot** [comment]
Yes, when I upgrade to the latest version of SecureCRT, it displays normally now

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Markus Gans ***@***.***>
发送时间: Sunday, May 15, 2022 2:21:36 AM
收件人: gansm/finalcut ***@***.***>
抄送: kmnot ***@***.***>; Author ***@***.***>
主题: Re: [gansm/finalcut] an exception is displayed when the string starts with more than six consecutive zeros (Issue #103)


Now I'm curious about what's going on, and I also installed SecureCRT. But I did not have the display problems of your screenshot.

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F12223838%2F168443808-d3e84ad9-1ef3-4363-b894-cc20eaf750b6.png&data=05%7C01%7C%7C5ac793fedfdb48213c5a08da35d69548%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637881493012773115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eKMIeYGkkaULtGVPI8rjGhksBkd9mKQcQJeeGp%2FcyvE%3D&reserved=0>

My terminal setting

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F12223838%2F168443820-784d6bce-901b-40ab-a9e4-1a40d764cd1c.png&data=05%7C01%7C%7C5ac793fedfdb48213c5a08da35d69548%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637881493012773115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7p71RdfDbI3mD4ucjUE2R59fX%2BIQuxSZdq8bXxWmRSo%3D&reserved=0>
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F12223838%2F168443825-3b9829b3-a40b-4119-b700-2a74bc9053c8.png&data=05%7C01%7C%7C5ac793fedfdb48213c5a08da35d69548%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637881493012773115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kNcG%2B5kjL348t0iHsUQPh2spAb90gdgHD2vhyof9IY4%3D&reserved=0>

I have tested with RHEL7 and the SecureCRT version 9.2.1 (build 2768)

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F12223838%2F168443833-e216a856-fe68-42a4-b348-79972dd1f3ff.png&data=05%7C01%7C%7C5ac793fedfdb48213c5a08da35d69548%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637881493012773115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pntUrcLO61EN5Uzn9BWBtYbC3VeJqomaon9O%2BsiUxRQ%3D&reserved=0>

―

**Comment by gansm** [comment]
It's great that you were able to solve your problem!
