### ISSUE TITLE
ColorPalette not resetting after close

### ISSUE THREAD

**Issue by wimstockman** [gansm/finalcut#115]
## ColorPalette not resetting after close

I see that finalcut sets its own colorpalette on startup.
But after quitting it doesn't revert back to the original.
I'm using St terminal emulator 

This is before:
![before](https://user-images.githubusercontent.com/5656539/216278719-05459816-abf9-468c-ad66-e073b8795d12.png)

And this is after:
![after](https://user-images.githubusercontent.com/5656539/216278815-a2c69bba-6df2-4a04-9a0f-bfbb44d6f34f.png)

Kind Regards,
Wim Stockman

**Comment by gansm** [comment]
Hi Wim, the st terminal has a poorly implemented OSC 104 (reset color palette). It supports no call without parameter (which means reset all). As a workaround, I reset each color separately (b291d04).


Therefore

```
"\033]104;0\007"
          :
"\033]104;15\007"
```

instead of

```
"\033]104\007"
```

**Comment by wimstockman** [comment]
Thanks for your solution.
Maybe I should sent a patch to st witch implementation for the OSC :-).
Great Work.
Have a nice weekend.
Wim
