### ISSUE TITLE
FListView Column Selection Feature

### ISSUE THREAD

**Issue by siddharth99** [gansm/finalcut#12]
I have been playing with the FListView widget this morning and it looks extremely helpful for our particular use case where we have use case to print nested tabular data (similar to treeview example). Currently, I don't see a easy way to click on a column and possibly sort based on it's values; I see that FListView directly interacts with strings so it may not be able to sort numerical data but even if the library was able to provide a generic callback for clicked-column I should probably be able to handle it in client code; possible swap FListViewItem inplace without creating new objects; maybe something like
std::sort(itemlist.begin(), itemlist.end(), sort_fn); would probably need to additionally do a static_cast<FListViewItem*>() and then possible lookup client data based on 1st column to get new position.

```
bool sort_fn(FObject* a, FObject* b) {
  auto* x = static_cast<FListViewItem*>(a);
  auto* y = static_cast<FListViewItem*>(b);
  auto& name_x = x->getText(0);
  auto& name_y = x->getText(1);
  // Get saved data from client code which has correct data-types
  auto& x_struct = data_map[name_x];
  auto& y_struct = data_map[name_y];
  return x_struct.temperature < y_struct.temparature;
}
```

**Comment by gansm** [comment]
Hello siddharth99, thank you for your interest in the FListView widget. 

Sorting by the content of a single column is a not yet implemented but planned extension of FListView. 

My idea for an implementation:
```cpp
void setSortColumn (int column, bool ascending);
```
(where column = -1 stands for sorting is disabled)

External data connection:
Every FListViewItem can store via “type erasure” a FWidget::data_ptr (also known as void*), which can be pointing to the original data. I have added a getData() and a setData() method for this in the last commit.

https://codedocs.xyz/gansm/finalcut/classfinalcut_1_1FListViewItem.html

So you have (even after sorting) a reference to the original data object.

Unfortunately, it is not so easy to implement the sort, because an expandable tree structure is a list with sub-lists. Therefore, the sort you propose would only sort the top level of this structure.

**Comment by siddharth99** [comment]
With the presence of setData() and getData() functions, I think we just need to be able to pass a compare_fn something similar to - std::function<bool(FListViewItem&, FListViewItem&)>.

```cpp
using CompareFn = std::function<bool(FListViewItem&, FListViewItem&>;
using CompareFns = std::vector<CompareFn>;

// This function will be called when we click on column name in UI
void FListView::setSortColumn (int column, bool ascending) {
  sort_column = column;
  sort_ascending = ascending;
}

// This function is called by client code to enable sorting on a particular column using a
// custom compare-fn. In most cases when client code uses this feature it will also use setData()
// at init to point to a custom struct. And within this compare-fn it will use getData() and do
// actual comparison on user data fields
void FListView::enableSorting(int column, CompareFn cmp_fn) {
  cmp_fns[column] = cmp_fn;
}

void FListView::sort() {
  if (sort_column != 0) {
    std::sort(listviewitems.begin(), listviewitems.end(), cmp_fns[sort_column]);
    for(auto&& item : listviewitems) {
      item.sort(cmp_fns[sort_column]);
    }
  }
}

std::vector<CompareFn> cmp_fns;
int sort_column = 0;
bool sort_ascending = false;

// In FListViewItem we have this recursive sort function
void FListViewItem::sort(CompareFn cmp_fn) {
  std::sort(sub_items.begin(), sub_items.end(), cmp_fn);
  // If there is multiple levels of nesting
  for (auto&& item : sub_items) {
    item.sort(cmp_fn);
  }
}
```

Also, in above code I'm registering a different compare function per column but we also have the option to register a single function that also takes the column number / name.

**Comment by gansm** [comment]
Thank you very much for your suggestions. I have now realized a sorting for the `FListView` widget. However, the implementation is only accessible via API and not via the user interface. Clicking on the column headings is not possible. There also is no sort indicator (arrow up and down) which shows the sort order.

It is possible to define the sort type for each column

```cpp
enum sorting_type
{
  by_name,
  by_number,
  user_defined,
  unknown
};
```
and the sort order to be applied to it.
```cpp
enum sorting_order
{
  ascending,
  descending,
  unsorted
};
```
The sort types `by_name` and `by_number` are built-in sort types. The sort type user_defined can be specified directly by the programmer. There are two methods for this: `setUserAscendingCompare()` and `setUserDescendingCompare()`.

A small example:
```cpp
bool sortAscending (const finalcut::FObject* lhs, const finalcut::FObject* rhs)
{
  const FListViewItem* l_item = static_cast<const FListViewItem*>(lhs);
  const int column = l_item->getSortColumn();
  const FString l_string = l_item->getText(column);
  ...
}

bool sortDescending (const finalcut::FObject* lhs, const finalcut::FObject* rhs)
{
  ...
}

// Create FListView object
listView = new finalcut::FListView (this);

// Populate FListView with data...

listView->setColumnSortType (1, finalcut::fc::by_name);
listView->setColumnSortType (2, finalcut::fc::user_defined);
listView->setColumnSortType (3, finalcut::fc::by_number);
listView->setColumnSort (2, finalcut::fc::ascending);
listView->setUserAscendingCompare(sortAscending);
listView->setUserDescendingCompare(sortDescending);
listView->sort();  // Perform sorting
```

**Comment by gansm** [comment]
FListView now has a clickable column heading to change the sort order.
The current sort order is indicated by the sort indicator (▼/▲).
