### ISSUE TITLE
Does it support MSYS2 MinGW64?

### ISSUE THREAD

**Issue by tn1997tn** [gansm/finalcut#120]
I found Cygwin is supported but there is no information about MSYS2.

**Comment by gansm** [comment]
Hi tn1997tn, I just set up a [MSYS2](https://www.msys2.org/) test environment and was able to successfully compile FINAL CUT there.

![grafik](https://user-images.githubusercontent.com/12223838/220594169-b29d637d-4582-4ad2-9c80-8e43690b8181.png)

**Comment by tn1997tn** [comment]
You used the MSYS Shell. I'm talking about the MINGW64 Shell (also part of MSYS2).
