### ISSUE TITLE
FListview hide columns

### ISSUE THREAD

**Issue by wimstockman** [gansm/finalcut#123]
## Feature Request
Hi Markus,

I was wondering if it  is possible or not to hide a column in the FListview widget.

I was thinking of two possible use cases:
1. One dynamically hiding view columns can be handy if there are a lot of columns.
2. For adding some rowid information, for instance when select the row. I can have a form with the rest of the info pulled out of a database.

Kind Regards,
Wim Stockman

**Comment by gansm** [comment]
Hi Wim, this is a great idea that I have just implemented.

![image](https://user-images.githubusercontent.com/12223838/230241548-3e4288e7-8ae3-441a-8473-0d651f29444b.png)

![image](https://user-images.githubusercontent.com/12223838/230241570-45a05ddd-1838-4baf-b07f-bd819001724e.png)

![image](https://user-images.githubusercontent.com/12223838/230241584-0b74e6b6-01b4-4122-a05f-6bad362f705a.png)

**Comment by wimstockman** [comment]
Hi Marcus,

Thanks for the quick implementation.
Keep up the good work !

Kind Regards,
Wim Stockman
