### ISSUE TITLE
can i recomend you guys an acscii 3d game

### ISSUE THREAD

**Issue by alavaelian** [gansm/finalcut#130]
maybe you would like to hear about a neat proyect, is a game enterly programmed in ascii and it is 3d and runs in the browser is just neat. http://asciicker.com/y8/ i am not the author of the proyect . https://ascii-patrol.com/area53/ascii-patrol-html5.html here is another proyect of the same author hoppe you enjoy it

**Comment by gansm** [comment]
Interesting, I was not aware of these projects.
Thanks for the two links.

**Comment by alavaelian** [comment]
and i just test it and it works on a terminal even inside of a tty and it is still 3d just neat
