### ISSUE TITLE
building problem with gcc-14

### ISSUE THREAD

**Issue by alexmyczko** [gansm/finalcut#140]
please take a look at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1074958

**Comment by gansm** [comment]
This is a bug I have already fixed upstream. I have now released an intermediate version 0.9.1 with a backport patch that allows FINAL CUT to be compiled with gcc 14. 

4dd5e6d

**Comment by alexmyczko** [comment]
thank you
