### ISSUE TITLE
layout support?

### ISSUE THREAD

**Issue by user1095108** [gansm/finalcut#16]
In other words, support for different text resolutions?

**Comment by gansm** [comment]
If you need a flexible layout, you can overload the `adjustSize()` method.
An example can be found in **examples/ui.cpp**.  

_Planned for the future is an FGrid widget container, which organizes its child widgets into rows and columns._

**Comment by user1095108** [comment]
The issue transcends adjusting the size to different screens. There exists a Turbo Vision port for Linux/Windows, that has implicit 80x25 assumptions. Nasty.

**Comment by gansm** [comment]
I'm afraid I don't understand the question. I can't see your point.
If you have a flexible layout, then it also works in 80x25.

**Comment by user1095108** [comment]
I was merely making a philosophical observation. Not only do layouts provide flexibility are regards different screen resolutions, they also guard us from making potentially invalid assumptions (like the 80x25 assumption in tvision). As for me personally, I was looking for a TUI library, that would support something like the Qt's `QScrollArea`, but no luck :(

BTW: If you intend to implement signals/slots, take a look at:
https://github.com/user1095108/generic/blob/master/callback.hpp

**Comment by gansm** [comment]
There is `FScrollView` that should be what you are looking for. For an example you can look into the **examples/scrollview.cpp** source code.

A callback functionality is already implemented. For example, you can use `emitCallback("clicked")` to generate a signal that can call a own routine via `widget.addCallback("clicked", F_METHOD_CALLBACK (this, &classname::method))`.
