### ISSUE TITLE
Compile error on Mac OS X

### ISSUE THREAD

**Issue by xmao** [gansm/finalcut#2]
Thank @gansm for this cool console widget library!

I am trying to compile on Mac OS X, and get the following errors possibly due to the missing of gpm library on Mac. Is there any way to fix quickly? Otherwise, is there any plan for support macOS?

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
Making all in fonts
make[3]: Nothing to be done for `all'.
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -Wall -Werror   -g -O2 -MT fscrollbar.lo -MD -MP -MF .deps/fscrollbar.Tpo -c -o fscrollbar.lo fscrollbar.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -Wall -Werror -g -O2 -MT fscrollbar.lo -MD -MP -MF .deps/fscrollbar.Tpo -c fscrollbar.cpp  -fno-common -DPIC -o .libs/fscrollbar.o
In file included from fscrollbar.cpp:4:
In file included from ./fscrollbar.h:31:
In file included from ./fwidget.h:74:
In file included from ./fvterm.h:29:
./fterm.h:33:12: fatal error: 'gpm.h' file not found
  #include <gpm.h>
           ^
1 error generated.
make[3]: *** [fscrollbar.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

```

**Comment by gansm** [comment]
Thank you for testing my widget library.

Your problem with the gpm.h is easy to fix. You just have to use the Parameter “--without-gpm” for the “configure” script.

But this might not be enough for a Mac OS X system. The whole library was primary develop to run under Linux. I've utilize system specifics like the Linux framebuffer and specific system device parameter like TIOCLINUX.  But a native BSD Unix support is planned for the distant future.

**Comment by xmao** [comment]
Thanks for prompt reply! 

Can finalcut works under terminal emulator like xterm as it uses linux frame buffer?

**Comment by gansm** [comment]
I just had the first successful compile run under macOS on Travis CI.

https://travis-ci.org/gansm/finalcut/jobs/304075891
