### ISSUE TITLE
cannot to compile finlacut

### ISSUE THREAD

**Issue by okbob** [gansm/finalcut#26]
I have a problem with compilation on Fedora 28
<pre>
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -Iinclude -Wall -Werror -DCOMPILE_FINAL_CUT   -g -O2 -MT foptimove.lo -MD -MP -MF .deps/foptimove.Tpo -c -o foptimove.lo foptimove.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -Iinclude -Wall -Werror -DCOMPILE_FINAL_CUT -g -O2 -MT foptimove.lo -MD -MP -MF .deps/foptimove.Tpo -c foptimove.cpp  -fPIC -DPIC -o .libs/foptimove.o
In member function ‘void finalcut::FOptiMove::rightMove(char*, int&, int, int)’,
    inlined from ‘int finalcut::FOptiMove::horizontalMove(char*, int, int)’ at foptimove.cpp:804:15,
    inlined from ‘int finalcut::FOptiMove::relativeMove(char*, int, int, int, int)’ at foptimove.cpp:687:28:
foptimove.cpp:819:18: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 512 equals destination size [-Werror=stringop-truncation]
     std::strncpy ( hmove
     ~~~~~~~~~~~~~^~~~~~~
                  , tparm(F_parm_right_cursor.cap, num, 0, 0, 0, 0, 0, 0, 0, 0)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  , BUF_SIZE );
                  ~~~~~~~~~~~~
In member function ‘bool finalcut::FOptiMove::isMethod0Faster(int&, int, int)’,
    inlined from ‘char* finalcut::FOptiMove::moveCursor(int, int, int, int)’ at foptimove.cpp:524:23:
foptimove.cpp:941:18: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 512 equals destination size [-Werror=stringop-truncation]
     std::strncpy (move_ptr, move_xy, BUF_SIZE);
     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [Makefile:694: foptimove.lo] Chyba 1
make[3]: Opouští se adresář „/home/pavel/src/finalcut/src“
make[2]: *** [Makefile:734: all-recursive] Chyba 1
make[2]: Opouští se adresář „/home/pavel/src/finalcut/src“
make[1]: *** [Makefile:493: all-recursive] Chyba 1
make[1]: Opouští se adresář „/home/pavel/src/finalcut“
make: *** [Makefile:379: all] Chyba 2
</pre>

**Comment by gansm** [comment]
It seems to be a problem with optimization level 2 (parameter -O2). I have fixed this problem in the current commit.

**Comment by okbob** [comment]
It is ok now. Thank you
