### ISSUE TITLE
building

### ISSUE THREAD

**Issue by WarShoe** [gansm/finalcut#3]
Configuration was fine, but 'make' returns:
....../finalcut/missing: line 81: aclocal-1.14: command not found
And my system does have aclocal-1.15

**Comment by WarShoe** [comment]
It was easy to fix the Makefile by using aclocal-1.15 and automake-1.15, but obviously the configuration script can be improved. Maybe you want to migrate to CMake at some moment?

**Comment by gansm** [comment]
Please try to run “autoreconf -v --install --force” before you use the configure script.
