### ISSUE TITLE
CJK support (wide character)

### ISSUE THREAD

**Issue by codehz** [gansm/finalcut#37]
Current: (example/input-dialog)

![image](https://user-images.githubusercontent.com/13158903/59606213-24569080-9143-11e9-977d-1779b827cda1.png)

**Comment by gansm** [comment]
This is absolutely correct, wide character are not yet supported by ＦＩＮＡＬ  ＣＵＴ in the current state of development.

**Comment by gansm** [comment]
I have committed (8c67f64) a new version that provides support for displaying full-width characters on the terminal. Using CJK characters should no longer be a problem.

However, the support for [combining character](https://en.wikipedia.org/wiki/Combining_character) has not yet been implemented.
    Example:  a°  ➝  å   ("\u0061\u030a")

**Comment by codehz** [comment]
It works perfectly!
All the components works with CJK characters/fullwidth characters

**Comment by gansm** [comment]
Thanks for testing and positive feedback.
