### ISSUE TITLE
Can't compile under Ubuntu

### ISSUE THREAD

**Issue by paradisiaca** [gansm/finalcut#44]
I tried to compile under Ubuntu 18.04 following the installation instructions, but it failed when running autoreconf

```
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:81: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

It failed while checking for c++11 capability

**Comment by gansm** [comment]
It looks like you have not installed "autoconf-archive".

You should check [here](https://github.com/gansm/finalcut/blob/master/doc/faq.md#what-do-i-need-to-build-this-library) if you have installed everything you need to build FINAL CUT.

**Comment by paradisiaca** [comment]
Now it works after installing "autoconf-archive", thank you.
