### ISSUE TITLE
any way to remove window borders?

### ISSUE THREAD

**Issue by basedtho** [gansm/finalcut#48]
i'd like to remove the red lines
![KG58jFm](https://user-images.githubusercontent.com/60894565/78855830-a515ae80-7a2d-11ea-823b-c4e24e03592e.png)

didn't find this in the docs

if there isn't, i wonder why, because we can remove shadows no problem

**Comment by gansm** [comment]
Thank you very much for your tip. This function did not exist before.

Please try my last commit (20c3cf2) with the following code:

```cpp
#include <final/final.h>

using finalcut::FPoint;
using finalcut::FSize;

int main (int argc, char* argv[])
{
  finalcut::FApplication app(argc, argv);
  finalcut::FDialog dialog(&app);
  dialog.setText ("Dialog");
  dialog.unsetBorder();  // Disable the dialog border
  dialog.setGeometry (FPoint(25, 6), FSize(32, 12));
  finalcut::FButton button{"&Quit", &dialog};
  button.setGeometry (FPoint(19, 8), FSize(10, 1), false);
  button.addCallback
  (
    "clicked",
    F_METHOD_CALLBACK (&dialog, &finalcut::FApplication::cb_exitApp),
    nullptr
  );
  app.setMainWidget(&dialog);
  dialog.show();
  return app.exec();
}
```

**Comment by basedtho** [comment]
@gansm thank you for the fastest response! works perfectly!
