### ISSUE TITLE
FListBoxItem: add a pointer to user data

### ISSUE THREAD

**Issue by WarShoe** [gansm/finalcut#5]
I suggest to enhance a bit FListBoxItem class by passing a user provided data pointer to the constructor. 

Change (I just picked up one of the three available constructors):
`   explicit FListBoxItem (const std::string&);`
To
`  explicit FListBoxItem (const std::string&,const void *data=0);`
Store 'data' attribute in FListBoxItem and provide access method to it.

The introduction of `data` will simplify the use of FListBox class. Consider the following example. There is a custom list `std::vector<MyData> mydata;`. A programmer wants a UI to select an item in the list and pass it to a function `void myfunction(const MyData &data);`. To achive this, the programmer has to:

1. Create FListBox object
2. Loop over **mydata** vector and create string presentations if every MyData item
3. When user selects an item, the code will access  FListBoxItem, which has (a) item "string" value and (b) item number
4. One should look back to the original **mydata** vector (which means the programmer has to keep the container it in the UI code) to access the selected MyData object.

With the proposed modification, the step (4) will not be needed. Think about situations when the original container is not vector, but list or map. In this case "item number" is more-or-less useless, and extra code should be written to keep the items connection.

**Comment by gansm** [comment]
Nice idea, I've implemented it spontaneously.

**Comment by WarShoe** [comment]
Access method `FListBoxItem::getData()` is missing.

**Comment by gansm** [comment]
The missing access method getData() is now implemented.
