### ISSUE TITLE
Display corruption?

### ISSUE THREAD

**Issue by lighth7015** [gansm/finalcut#50]
Button shadows display weird in Konsole, Alacritty and several other terminal emulators. Alacritty simply displays squares for all of the UI characters.
![image](https://user-images.githubusercontent.com/671336/80381904-9e7d9880-886f-11ea-9529-5d7769bfb669.png)

**Comment by gansm** [comment]
This looks like a badly designed font to me. The Unicode character " ▀ " (U+2580) is a block element and should fill the entire character width.

https://www.compart.com/de/unicode/U+2580

Am I right in assuming that
```bash
echo -e "\u2580\u2580\u2580"
```
causes the same effect in your terminal?

**Comment by lighth7015** [comment]
It looks fine on the actual terminal
