### ISSUE TITLE
Iconizable windows?

### ISSUE THREAD

**Issue by lighth7015** [gansm/finalcut#52]
Hi, I just noticed this, apologies for the flurry of tickets.

Anyway, I was wondering if it was possible to change(?) the default UI style to be more in-line with VBDOS?

Thanks!

e.g.
![image](https://user-images.githubusercontent.com/671336/80400204-7a7a8100-8888-11ea-97ca-3b5fba58318b.png)

**Comment by gansm** [comment]
A widget-theming is not planned at the moment. However, I am planning to introduce a dark-color theme. Here is a first draft:

![finalcut-menu-dark-theme](https://user-images.githubusercontent.com/12223838/80421087-33b67680-88dc-11ea-917b-db912b7182cf.png)

FINAL CUT is also used on Solaris and BSD text consoles, so you may not always have the full CP437 character set available. Often you only have 7-bit ASCII and the vt100 line characters.

http://fileformats.archiveteam.org/wiki/DEC_Special_Graphics_Character_Set

However, you can override the virtual method draw() of a widget in a derived class and customize the look and feel for yourself.

**Comment by lighth7015** [comment]
I was more wondering if iconizing (e.g. minimizing) windows was a thing that was planned. :D

**Comment by sdimaio** [comment]
Really great job.

**Comment by gansm** [comment]
Thank you

**Comment by lighth7015** [comment]
For instance,
![image](https://user-images.githubusercontent.com/671336/80421945-49f80e80-88ab-11ea-8f9e-edff67941193.png)

That was the other part of my question.

**Comment by lighth7015** [comment]
Apologies for not mentioning it before, btw!

**Comment by gansm** [comment]
OK, now I understand the meaning of your headline as well. 💡

The iconization of a window is not a nice concept. The text icons (it is not really an icon) are mostly hidden by other windows. So that you often search for them. This could also be the reason why the Borland Pascal IDE (Turbo Vision) does not support this too. Programs often use a status bar, rarely is there room for an additional window bar. Here I am still waiting for a golden idea.

**Comment by lighth7015** [comment]
It's just a frame like that which you can drag around the screen like a widget that you double-click to restore. I mean honestly you would just 'hide' the inner contents until the window is restored. It's just the way you render minimized windows :p

**Comment by gansm** [comment]
Thanks for your implementation tip. But my opinion about the icon concept is still the same. But I need a solution that cannot be covered by other windows.

**Comment by lighth7015** [comment]
And that's fine. Now the question shifts to, how I can implement it, where would I look? :p

**Comment by gansm** [comment]
I have a new version (042bd4c) that supports minimizing windows. For all FDialog widgets, you can enable this functionality with the `setMinimizable()` method. When you press the minimize button, the window rolls up into its title bar, and the window entry in the FDialogListMenu gets the addition "(minimized)".

![image](https://user-images.githubusercontent.com/12223838/126914867-a030783d-6dbb-4a87-a012-aeb9ce6f55ca.png)

**Comment by lighth7015** [comment]
You rock! :D
