### ISSUE TITLE
term attributes on Windows with Cygwin

### ISSUE THREAD

**Issue by abreu20011** [gansm/finalcut#56]
It's Windows' terminal capable tu use some of the xterm-256color features? 
I ran term-attributes.exe but the next features don't seems to works:

- Double underline
- Crossed-out
- Blink
- Invisible
- Protected

![2020-05-05 00_48_02-D__Development_finalcut_examples_term-attributes exe](https://user-images.githubusercontent.com/3339385/81020880-22381600-8e6a-11ea-9324-873c5a00cc37.png)

**Comment by gansm** [comment]
This depends on the capabilities and settings of your terminal. [Mintty](https://mintty.github.io/) should be able to display all supported capabilities of FINAL CUT. 

![mintty](https://user-images.githubusercontent.com/12223838/81025432-efe0e580-8e76-11ea-8d89-70d7bdcfc81f.png)

**Comment by abreu20011** [comment]
Except blink, all the options works

**Comment by gansm** [comment]
You have to enable this explicitly with "Allow blinking" _(see screenshot)_.

**Comment by abreu20011** [comment]
Nice! :D
thank so much
