### ISSUE TITLE
CMake integration

### ISSUE THREAD

**Issue by ghost** [gansm/finalcut#61]
Hello dear team,
I am trying to integrate this project into an existing CMake based project. 
Before I spend more time on this, is there an existing migration that someone did? 

Many thanks.

**Comment by gansm** [comment]
Now that the questioner's account has been deleted and there is no further activity here, I am closing this issue.

**Comment by gansm** [comment]
I have just discovered this fork (untested):

https://github.com/gatekeep/finalcut-cmake
