### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by siddharth99** [gansm/finalcut#64]
1. I am having a little difficulty trying to understand the memory-model; particularly with local / member variables. Say, I create 2  FDialog's diag1 & diag2 and 1 FLabel. Now, based on a click event I change the parent window of FLabel from diag1 to diag2 and vice-versa. My code looks something like this:
```
FLabel label;
FDialog diag1(fapp), diag2(fapp);
diag1.addChild(label);

// And in some callback I do
diag2.addChild(label);
```
All is expected to work fine till now. However, if I destruct diag1 or diag2 then it'll also try to destruct FLabel; at this point am I expected to see a memory corruption / seg-fault given that FLabel is on the stack and not heap. Overall, I am having a little difficult with the memory-model; should I always construct stuff on the heap or there a different way to think about the memory-model ?

2. Small point but when I have multiple dialog windows; closing any of them creates a confirmation dialog that says do you want to quit the program but in the end it'll only close the window. If I always operate on multiple dialogs what's the correct way to either override this message so it says close window OR correct way to always make it close the complete app ?
```
    void onClose(FCloseEvent* ev) {
      FApplication::closeConfirmationDialog(this, ev);
    }
```

3. Dynamic Widgets: I am trying to work with the scrollview.cpp example to make it resizable. I am able to get quite far but I want to understand the different functions a little better. The process I'm following based on the dynamic layout (size-adjustment.cpp) is as follows; is this correct ? I'm going to have a few different types of dialog boxes that will have a dynamic layout so I plan to follow the same convention for all of them ?
```
    # Override these 3 functions
    void setSize(const FSize& size, bool adjust) override;
    void adjustSize() override;
    void draw() override;

# This code is always fixed; just copy/paste it
void Scrollviewdemo::setSize(const FSize& size, bool adjust) {
  // Calling super class methods setSize() + adjustSize()
  FDialog::setSize (size, false);
  FDialog::adjustSize();
}

# Here, call the base class version and change the widget size if required
void Scrollviewdemo::adjustSize() {
  FDialog::adjustSize();
  // Change widget size (centerDialog())
}

# Here, adjustWidgets() and then call base class function
void Scrollviewdemo::draw() {
  adjustWidgets();
  // Calling super class method draw()
  FDialog::draw();
}
```

4. I played around the scrollview.cpp (making it dynamic) and menu.cpp and merged the 2 examples. It is working fine in terms of functionality but when I exit the app it screws up the terminal; the cursor disappears and new line is skipped too. Please advise if you can spot the issue. Also, any general advise based on this code. Please see attached code.

[my_test.txt](https://github.com/gansm/finalcut/files/5250527/my_test.txt)

**Comment by gansm** [comment]
> 1. I am having a little difficulty trying to understand the memory-model; particularly with > local / member variables. Say, I create 2  FDialog's diag1 & diag2 and 1 FLabel. Now, based > on a click event I change the parent window of FLabel from diag1 to diag2 and vice-versa. > > My code looks something like this:
> ```
> FLabel label;
> FDialog diag1(fapp), diag2(fapp);
> diag1.addChild(label);
> 
> // And in some callback I do
> diag2.addChild(label);
> ```
> 
> All is expected to work fine till now. However, if I destruct diag1 or diag2 then it'll also try to destruct FLabel; at this point am I expected to see a memory corruption / seg-fault given that FLabel is on the stack and not heap. Overall, I am having a little difficult with the memory-model; should I always construct stuff on the heap or there a different way to think about the memory-model ?


Hello siddharth99, thanks for the hint. This aspect is indeed still undocumented. I'll try to explain the basic structure in more detail:

**Widgets**

FINAL CUT has many widgets. It offers buttons, input fields, menus, and dialog boxes that cover the most common use cases. Widgets are visual elements that are combined to create user interfaces. Own widgets can be easily created by creating a derived class of FWidget or other existing widgets. All widgets are instances of [FWidget](https://codedocs.xyz/gansm/finalcut/classfinalcut_1_1FWidget.html) or its subclasses.

A widget can contain any number of child widgets. Child widgets are displayed in the display area of the parent widget. Window widgets based on 'FWindow' have their own virtual display area and are independent of the parent widget. 

When a parent widget is disabled, hidden, or deleted, the same operation is used recursively to all its child widgets. The base class `FObject` implements the self-organized object tree behavior. For example, `addChild()` removes the child ownership from an existing parent object before assigning it to the new target. When a child becomes deleted, the parent-child relationship causes its reference in the parent object to be removed. An explicit `delChild()` is no longer required here.


**Widget tree**

An `FApplication` widget is the top-level widget of an application. It is unique and can not have a parent widget. The class `FApplication` manages all settings and assigns keyboard and mouse input to the different widgets.

The main widget of a FINAL CUT application is the only object that `FApplication` can have as a child. This main widget is usually a window object that contains all sub-widgets of the application. A sub-widget can also be another window.

```
              ┌──────────────┐
Parent:       │ FApplication │     Application (= 1)
              └──────────────┘
                     ↓
                ┌─────────┐
Child:          │ FDialog │        Main widget (= 1)
                └─────────┘
                  ↓     ↓
           ┌────────┐ ┌─────────┐
Subchild:  │ FLabel │ │ FDialog │  Widget(s) of the main widget (≥ 1)
           └────────┘ └─────────┘
                           ↓ 
                       ┌────────┐
Sub-subchild:          │ FLabel │  Widget(s) from the parent widget (≥ 1)
                       └────────┘
                           ↓
                         [etc.]
```

After this little digression now back to your first question:

For the object lifetime, I would always prefer scoped objects ([RAII](http://www.modernescpp.com/index.php/garbage-collectio-no-thanks)). The destruction is done in reverse order of the definition.

```cpp
#include <iostream>
#include <final/final.h>

using finalcut::FPoint;
using finalcut::FSize;
finalcut::FApplication* app_ptr{nullptr};
finalcut::FDialog* dialog_ptr{nullptr};
finalcut::FLabel* label_ptr{nullptr};
finalcut::FButton* button_ptr{nullptr};


void operator delete (void* ptr) noexcept
{
  finalcut::FLog& log = *finalcut::FApplication::getLog();

  if ( ptr == app_ptr
    || ptr == dialog_ptr
    || ptr == label_ptr
    || ptr == button_ptr )
  {
    const char* widget_type = [&ptr]()
    {
      if ( ptr == app_ptr ) return "FApplication";
      if ( ptr == dialog_ptr ) return "FDialog";
      if ( ptr == label_ptr ) return "FLabel";
      if ( ptr == button_ptr ) return "FButton";
      return "?";
    }();
  
    std::clog << "-> Delete " << widget_type << std::endl;
  }

  std::free(ptr);
}

int main (int argc, char* argv[])
{
  // Logging
  std::ofstream out("/tmp/delete-order.log", std::ofstream::out | std::ofstream::app);
  std::streambuf* save_rdbuf = std::cout.rdbuf();
  std::clog.rdbuf(out.rdbuf());
  std::clog  << "[Begin]" << std::endl;

  // Application

  //---------------------------- variant a -----------------------------
  bool use_main_scope_for_fapplication{false};
  finalcut::FApplication* app = new finalcut::FApplication(argc, argv);

  //---------------------------- variant b -----------------------------
  //bool use_main_scope_for_fapplication{true};
  //finalcut::FApplication app_in_scope(argc, argv);
  //finalcut::FApplication* app = &app_in_scope;

  app_ptr = app;
  finalcut::FDialog* dialog = new finalcut::FDialog(app);
  dialog_ptr = dialog;
  dialog->setText ("Dialog");
  dialog->setGeometry (FPoint(40, 8), FSize(15, 9));
  finalcut::FLabel* label = new finalcut::FLabel{"Label", dialog};
  label_ptr = label;
  label->setGeometry (FPoint(5, 2), FSize(5, 1), false);
  finalcut::FButton* button = new finalcut::FButton{"&Quit", dialog};
  button_ptr = button;
  button->setGeometry (FPoint(2, 5), FSize(10, 1), false);
  button->addCallback
  (
    "clicked",
    finalcut::getFApplication(),
    &finalcut::FApplication::cb_exitApp,
    dialog
  );
  app_ptr->setMainWidget(dialog);


  dialog->show();

  int ret = app->exec();

  if ( ! use_main_scope_for_fapplication )
    delete app;

  std::clog  << "[End]" << std::endl;
  std::cout.rdbuf(save_rdbuf);  
  out.close();
  return ret;
}
```

Variant a
```bash
> tail -f /tmp/delete-order.log
[Begin]
-> Delete FLabel
-> Delete FButton
-> Delete FDialog
-> Delete FApplication
[End]
```

Variant b
```bash
> tail -f /tmp/delete-order.log
[Begin]
[End]
```

Both variants have no memory leak. The right allocation order is important here to avoid surprises.

_I will answer questions 2 to 4 later..._

**Comment by siddharth99** [comment]
Thanks for your reply! I'm getting a hang of the memory-model now. My current design has a lot of different modules (not related to TUI) but they may or may not expose a interface that can be plugged into the TUI so I'm going to keep all of individual dialog boxes on the heap since they can be constructed at different times but within a dialog box if the relation is well-established then it'll be best to have the smaller widgets as member variables / RAII.

On the close-event; I plan to go ahead with the menu-bar that has a Quit functionality. Since, I have multiple dialog boxes and don't have a main dialog this seems as the best option. Individual dialog boxes can be closed and to quit the app one can do it through the menu-bar.

I'll go through the dynamic-sizing example and the code changes you make for my_test.cpp and let you know if I have more questions.

Thanks again!
