### ISSUE TITLE
syntax error near unexpected token `CPPUNIT,'

### ISSUE THREAD

**Issue by jeffrey-a-meunier** [gansm/finalcut#65]
When trying to install finalcut on Ubuntu Server 20.04, at the step `./configure --prefix=/usr` I get this error:
```
configure: creating ./config.lt
config.lt: creating libtool
checking whether C++ compiler accepts -std=c++11... yes
checking for Gpm_Open in -lgpm... no
./configure: line 14053: syntax error near unexpected token `CPPUNIT,'
./configure: line 14053: `  PKG_CHECK_MODULES(CPPUNIT,'
```

I've installed `libtool`, `autconf`, `autoconf-archive`, `gpm`, `libcppunit-dev`, `pkg-config`, `libglib2.0-dev`, `libtinfo-dev`, `libncurses5-dev`, `libgpm-dev`.

`libstdc++-6-dev` isn't available for some reason.

 Any idea what I'm missing?

**Comment by gansm** [comment]
It looks like you have forgotten to install pkg-config.

```bash
> sudo apt-get install pkg-config
> autoreconf --install --force
> ./configure --prefix=/usr
```

**Comment by jeffrey-a-meunier** [comment]
Weird, `pkg-config` was already installed, but I deleted the whole source directory and re-cloned the repo and now it compiles and installs correctly. I guess one of my previous intermediate steps left something in an inconsistent state.

Thanks for the reply!
