### ISSUE TITLE
I want a graph function

### ISSUE THREAD

**Issue by alavaelian** [gansm/finalcut#67]
hello every body how i can draw a function uisnt this library if thas is posible

**Comment by gansm** [comment]
In principle, FINAL CUT can everything conceivable in terminal characters realized.

Do you want to draw mathematical functions, such as a sine curve?
Or would you like to have a graphical representation on the screen to visualize any measured variable?

**Comment by alavaelian** [comment]
> In principle, FINAL CUT can everything conceivable in terminal characters realized.
> 
> Do you want to draw mathematical functions, such as a sine curve?
> Or would you like to have a graphical representation on the screen to visualize any measured variable?

i want to draw a mathematical functions, like a curve yes

**Comment by alavaelian** [comment]
> In principle, FINAL CUT can everything conceivable in terminal characters realized.
> 
> Do you want to draw mathematical functions, such as a sine curve?
> Or would you like to have a graphical representation on the screen to visualize any measured variable?

and a X|Y table f its is posible but i dont now how

**Comment by gansm** [comment]
You could realize it for example as follows:

```cpp
#include <final/final.h>

using namespace finalcut;

class Graph : public FDialog
{
  public:
    explicit Graph (FWidget* parent = nullptr)
      : FDialog{parent}
    {
      setText ("Curve plotting");
      setGeometry (FPoint{10, 5}, FSize{61, 18});
    }

    void draw() override
    {
      FDialog::draw();  // Calling super class method draw()

      int h = int(getClientHeight());
      int w = int(getClientWidth());
      print() << FPoint{3, 3}
              << FColorPair{fc::Black, fc::White}
              << "f(x)";
      
      for (int y = 0; y < h - 4; y++)
      {
        print() << FPoint{5, h - y} << fc::BoxDrawingsVertical;  // │

        if ( y % 5 == 0 )
        {
          FString num = FString().setNumber(y);
          print() << FPoint{5 - int(num.getLength()), h - y}
                  << num
                  << fc::BoxDrawingsVerticalAndLeft;  // ┤
        }
      }

      for (int x = 0; x < w - 8; x++)
      {
        print() << FPoint{6 + x, h + 1} << fc::BoxDrawingsHorizontal; // ─

        if ( x % 10 == 0 )
        {
          print() << FPoint{6 + x, h + 2}
                  << x
                  << FPoint{6 + x, h + 1}
                  << fc::BoxDrawingsDownAndHorizontal;  // ┬
        }
      }

      print() << fc::BlackRightPointingPointer  // ►
              << " x"
              << FPoint{5, 4} << fc::BlackUpPointingTriangle  // ▲
              << FPoint{5, h + 1} << fc::BoxDrawingsUpAndRight;  // └
    }   
};

class Plot : public Graph
{
  public:
    explicit Plot (FWidget* parent = nullptr)
      : Graph{parent}
    { }

  void draw() override
  {
    Graph::draw();  // Calling super class method draw()

    int h = int(getClientHeight());
    int w = int(getClientWidth());
    wchar_t dot = L'o';
    FPoint origin{6, h};  // Pos(0,0)
    print() << FColorPair{fc::Blue, fc::White};

    for (int x = 0; x < w - 8; x++)
    {
      int y = int(-3.1 * std::cos(double(x)/3.1) + 3.9);
      print() << (origin + FPoint(x, -y))
              << dot;
    }
  }
};

int main (int argc, char* argv[])
{
  FApplication app(argc, argv);
  Plot dialog(&app);
  FWidget::setMainWidget(&dialog);
  dialog.show();
  return app.exec();
}
```

![image](https://user-images.githubusercontent.com/12223838/94351193-a9bf3500-0056-11eb-98d1-1b8a4cf4715f.png)

**Comment by alavaelian** [comment]
Ok dude that is relly  amazing  how si yo u learn to do  that.is Tere some book yo learn final cut

**Comment by gansm** [comment]
There is no book about FINAL CUT. But I have a small online documentation for you: [The FINAL CUT introduction](https://github.com/gansm/finalcut/wiki/Getting-Started#getting-started-with-the-final-cut-widget-toolkit)

**Comment by alavaelian** [comment]
many thanks mam

**Comment by alavaelian** [comment]
> You could realize it for example as follows:
> 
> ```c++
> #include <final/final.h>
> 
> using namespace finalcut;
> 
> class Graph : public FDialog
> {
>   public:
>     explicit Graph (FWidget* parent = nullptr)
>       : FDialog{parent}
>     {
>       setText ("Curve plotting");
>       setGeometry (FPoint{10, 5}, FSize{61, 18});
>     }
> 
>     void draw() override
>     {
>       FDialog::draw();  // Calling super class method draw()
> 
>       int h = int(getClientHeight());
>       int w = int(getClientWidth());
>       print() << FPoint{3, 3}
>               << FColorPair{FColor::Black, FColor::White}
>               << "f(x)";
> 
>       for (int y = 0; y < h - 4; y++)
>       {
>         print() << FPoint{5, h - y} << UniChar::BoxDrawingsVertical;  // │
> 
>         if ( y % 5 == 0 )
>         {
>           FString num = FString().setNumber(y);
>           print() << FPoint{5 - int(num.getLength()), h - y}
>                   << num
>                   << UniChar::BoxDrawingsVerticalAndLeft;  // ┤
>         }
>       }
> 
>       for (int x = 0; x < w - 8; x++)
>       {
>         print() << FPoint{6 + x, h + 1} << UniChar::BoxDrawingsHorizontal; // ─
> 
>         if ( x % 10 == 0 )
>         {
>           print() << FPoint{6 + x, h + 2}
>                   << x
>                   << FPoint{6 + x, h + 1}
>                   << UniChar::BoxDrawingsDownAndHorizontal;  // ┬
>         }
>       }
> 
>       print() << UniChar::BlackRightPointingPointer  // ►
>               << " x"
>               << FPoint{5, 4} << UniChar::BlackUpPointingTriangle  // ▲
>               << FPoint{5, h + 1} << UniChar::BoxDrawingsUpAndRight;  // └
>     }   
> };
> 
> class Plot : public Graph
> {
>   public:
>     explicit Plot (FWidget* parent = nullptr)
>       : Graph{parent}
>     { }
> 
>   void draw() override
>   {
>     Graph::draw();  // Calling super class method draw()
> 
>     int h = int(getClientHeight());
>     int w = int(getClientWidth());
>     wchar_t dot = L'o';
>     FPoint origin{6, h};  // Pos(0,0)
>     print() << FColorPair{FColor::Blue, FColor::White};
> 
>     for (int x = 0; x < w - 8; x++)
>     {
>       int y = int(-3.1 * std::cos(double(x)/3.1) + 3.9);
>       print() << (origin + FPoint(x, -y))
>               << dot;
>     }
>   }
> };
> 
> int main (int argc, char* argv[])
> {
>   FApplication app(argc, argv);
>   Plot dialog(&app);
>   FWidget::setMainWidget(&dialog);
>   dialog.show();
>   return app.exec();
> }
> ```
> 
> _Last modified: Code changes for the new scoped enumeration data types_
> 
> ![image](https://user-images.githubusercontent.com/12223838/94351193-a9bf3500-0056-11eb-98d1-1b8a4cf4715f.png)
> 
> _f(x)_ = −3.1 ∙ cos( _x_ / 3.1 ) + 3.9

pretty neat that you have change this that is some deditation
