### ISSUE TITLE
Wrong conversion std::string->FString->std::string

### ISSUE THREAD

**Issue by WarShoe** [gansm/finalcut#7]
The assertion is triggered in the code below. This is really nasty :(
```
    std::string s1="abc";
    FString s2=s1;
    std::string s3=s2.toString();
    assert(s1==s3);

```

**Comment by WarShoe** [comment]
I just had a look into your FString code. My first impression is that you are reinventing the work of std::string. There are lots of similar function in the standard C++. And if you need more functionality one can use a very powerful and flexible fmt::format library https://github.com/fmtlib/fmt.
Instead of custom (and unsafe!) definitions of `typedef unsigned int   uInt32;` one should use the standard <cstdint> include types http://www.cplusplus.com/reference/cstdint. This should greatly improve portability of your code anyway. I am just curious, what was the idea behind development of FString class? Was it because of the UTF8 support, or something else? Honestly, the class looks awkward (sorry for the criticism!).

**Comment by gansm** [comment]
The code work as designed! The argument expression s1 == s3 compares two  pointer and not the characters of the strings.

```
10         assert(s1==s3);
(gdb) p s1
$7 = "abc"
(gdb) p s3
$9 = "abc"
(gdb) p &s1
$10 = (std::string *) 0x7fffffffde10
(gdb) p &s3
$11 = (std::string *) 0x7fffffffde00
```

FString is already tailored to it own needs. It should work together with all variants of strings or wide strings. I'll have a look at fmt::format. The use of `typedef uint32_t uInt32;`  would in fact increase standard compliance.

**Comment by WarShoe** [comment]
```
    std::string s1="abc";
    FString s2=s1;
    std::string s3=s2.toString();
    std::string s4=s1;
    std::cout << "Is s1 equal to s4? " << (s1==s4?"true":"false") << std::endl;
    std::cout << "Is s1 equal to s3? " << (s1==s3?"true":"false") << std::endl;
    std::cout << "s1.length()=" << s1.length() << "  s3.length()=" << s3.length() << std::endl;

```
OUTPUT:
Is s1 equal to s4? true
Is s1 equal to s3? false
s1.length()=3  s3.length()=4

It seems there is an extra invisible trailing zero at the end of s3 string.

**Comment by WarShoe** [comment]
```
const std::string FString::toString() const
{
  return std::string(c_str(), length+1);
}

```

and this is the code. Why do you set length+1?! This is the place where the trailing zero is inserted to the resulted std::string.

**Comment by gansm** [comment]
You are absolutely right!
A std::string is no null-terminated string and required no "+ 1".
I have just fixed this in the code.
