### ISSUE TITLE
cannot derive from ‘final’ base ‘finalcut::FWidgetColors’ in derived type ‘BeeColorTheme’

### ISSUE THREAD

**Issue by AndreiSva** [gansm/finalcut#71]
Im following along with the color themes tutorial and im having a bit of trouble getting it to work.

**Comment by gansm** [comment]
You only have to create the two header files, the cpp file, and compile it. I have attached these three files as a zip file. Please try to compile it.

```bash
g++ theme.cpp -o theme -O2 -lfinal -std=c++11
```

[user-theme-example.zip](https://github.com/gansm/finalcut/files/5352766/user-theme-example.zip)

**Comment by AndreiSva** [comment]
I've tried compiling the files using the command you suggested and it still throws a compilation error. Here is the full stack trace:
[stack_trace.txt](https://github.com/gansm/finalcut/files/5352888/stack_trace.txt)

**Comment by gansm** [comment]
Is it possible that you have installed version 0.6.0? User themes are a feature of the upcoming version 0.7.0, so you should work with the current git commit (73e587b).

```bash
git clone git://github.com/gansm/finalcut.git
```

**Comment by AndreiSva** [comment]
Thank you! I just downloaded the latest amd64 release i could find on the release page. compiling worked fine after the new install. You make an amazing library!

**Comment by gansm** [comment]
Thank you very much
