### ISSUE TITLE
table with final cut

### ISSUE THREAD

**Issue by alavaelian** [gansm/finalcut#73]
i wanna draw a table in final cut

**Comment by gansm** [comment]
I can recommend the [FListView](https://codedocs.xyz/gansm/finalcut/classfinalcut_1_1FListView.html) widget for this.

You can look at this sample code: [listview.cpp](https://github.com/gansm/finalcut/blob/master/examples/listview.cpp)

![grafik](https://user-images.githubusercontent.com/12223838/95685840-b321d300-0bfa-11eb-99aa-dfa2ed30dca4.png)

**Comment by alavaelian** [comment]
thanks again dude
