### ISSUE TITLE
i wanna help to understanding call backs and  how to use this api 

### ISSUE THREAD

**Issue by alavaelian** [gansm/finalcut#75]
i wanna material to make aplications with final cut but i dont now how to start

**Comment by gansm** [comment]
It is an implementation of the classic [callback functions](https://en.wikipedia.org/wiki/Callback_(computer_programming)) to automatically call your own function when a specific action (the signal) occurs. I have explained this on the wiki pages with some examples:

https://github.com/gansm/finalcut/wiki/Signals-and-Callbacks#signals-and-callbacks

For example, do you have a function `cb_func()` that should be called when the `"focus-in"` signal will be sent?  Then you can connect this signal to your callback function.


```cpp
void cb_func()
{
  // Do something…
}

int main (int argc, char* argv[])
{
  FApplication app(argc, argv);
  FDialog dialog(&app);
  FLineEdit input(dialog);

  // Connect the input field signal "focus-in" to the callback function cb_func()
  input.addCallback
  (
    "focus-in",  // Callback signal
    &cb_func     // Function pointer
  );
  …
}
```

**Comment by alavaelian** [comment]
thaks again dude some there are a posibillty to make a more fully guide thats full will be great man , and another thing can you recomend me a book to learn c++

**Comment by gansm** [comment]
For the documentation, I have limited myself to the core aspects of FINAL CUT. It is supplemented by the example programs, which cover the code almost completely. But the documentation is not finished yet and will be extended from time to time.

If you want to know more about C++, you should take a look at these pages:
* https://www.learncpp.com/
* http://www.cplusplus.com/reference/
* https://en.cppreference.com/w/Main_Page
* https://isocpp.org/faq
* https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html

**Comment by alavaelian** [comment]
thanks dude
