### ISSUE TITLE
games with finalcut?

### ISSUE THREAD

**Issue by alavaelian** [gansm/finalcut#77]
is there possible make game with final cut or maybe in the future you can include a game implementation in final cut

**Comment by gansm** [comment]
FINAL CUT fulfills all requirements to develop an interactive game.
But unfortunately, I am not an ASCII artist who can create a scene like this:
![grafik](https://user-images.githubusercontent.com/12223838/96578654-d2dd8900-12d5-11eb-8419-800af1068b19.png)

**Comment by sdimaio** [comment]
Amazing!. You are great!

**Comment by gansm** [comment]
You misunderstood me! That's not mine.
The picture came from here:
http://cecilsunkure.blogspot.com/2011/11/windows-console-game-setting-up-window.html

**Comment by alavaelian** [comment]
well that is very good
