### ISSUE TITLE
finalcut vs  turbovision

### ISSUE THREAD

**Issue by alavaelian** [gansm/finalcut#78]
what have more features

**Comment by gansm** [comment]
The functionality of both frameworks is quite identical. [Turbo Vision](https://en.wikipedia.org/wiki/Turbo_Vision) is 30 years old legacy code from the [Borland Software Corporation](https://en.wikipedia.org/wiki/Borland). Many publications describe the use of Turbo Vision during this period. So Turbo Vision has to watch out for backward compatibility of its API. FINAL CUT is not restricted in this way.

**Comment by alavaelian** [comment]
ok

**Comment by user1095108** [comment]
TV had problems on non 80x25 terminals last time I checked.
