### ISSUE TITLE
Request for project files for the Community

### ISSUE THREAD

**Issue by hwpplayer1** [gansm/finalcut#81]
As i learned from GitHub standards there we need Contributors, Code of Conduct and issue templates for the bug reports.

I wish you best luck, and please do stay safe. 

Happy Hacking!

**Comment by gansm** [comment]
It is done. Thank you for the hint.

- [x] [Contributing](/gansm/finalcut/blob/main/Contributing.md)
- [x] [Code of Conduct](/gansm/finalcut/blob/main/CODE_OF_CONDUCT.md)
- [x] [Bug report](/gansm/finalcut/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
- [x] [Feature request](/gansm/finalcut/blob/main/.github/ISSUE_TEMPLATE/feature_request.md)
- [x] [Report a security vulnerability](/gansm/finalcut/blob/main/SECURITY.md)

**Comment by hwpplayer1** [comment]
Thanks See you again
