### ISSUE TITLE
conflict between finalcut and other libearies (deal.II, trilinos, boost,etc.) 

### ISSUE THREAD

**Issue by euroboros** [gansm/finalcut#82]
Hello, Dear Markus,
I plan to build a text UI project to read parameter file of deal.II applications
The separate UI works, but it failed the compilation when I include headers of both Deal.II and finalcut in a single source file by, 
    #include <deal.II/base/parameter_handler.h>
    using namespace dealii;
    #include <final/final.h>
    using namespace finalcut;
Note deal.II also include some headers of trilinos and boost library,
It seems some objects in finalcut headers conflict with the version in trilinos and boost.
Please see the following information
Many thanks for your nice final cut and any possible help!
Zhenyu

```shell
In file included from /home/zhenyu/deps/finalcut/include/final/ftermcap.h:51:0,
                 from /home/zhenyu/deps/finalcut/include/final/final.h:80,
                 from /home/zhenyu/work/icarusii/paradox/finalcut/paradox.cpp:28:
/home/zhenyu/deps/trilinos_12.12.1/include/Kokkos_Concepts.hpp:141:49: error: expected ‘)’ before ‘*’ token
   typedef Device<execution_space,memory_space>  device_type;
/home/zhenyu/deps/trilinos_12.12.1/include/impl/Kokkos_TaskQueue.hpp:138:20: error: ‘memory_pool’ does not name a type; did you mean ‘MemoryPool’?
   TaskQueue( const memory_pool & arg_memory_pool );
                    ^~~~~~~~~~~
                    MemoryPool
/home/zhenyu/deps/trilinos_12.12.1/include/Teuchos_FancyOStream.hpp:1135:13:   required from ‘std::streamsize Teuchos::basic_FancyOStream_buf<CharT, Traits>::xsputn(const char_type*, std::streamsize) [with CharT = char; Traits = std::char_traits<char>; std::streamsize = long int; Teuchos::basic_FancyOStream_buf<CharT, Traits>::char_type = char]’
/home/zhenyu/work/icarusii/paradox/paradox_main.cpp:323:1:   required from here
/home/zhenyu/deps/trilinos_12.12.1/include/Teuchos_FancyOStream.hpp:1180:15: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
       if(s[p] == newline) {
```

**Comment by gansm** [comment]
Hello Zhenyu,

you have already correctly identified your problem.
There is a name collision!

The reason should be lines
```cpp
  using namespace dealii;
```
and
```cpp
  using namespace finalcut;
```

For more detail you can read the [C++ Core Guideline rule SF.7](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file).


_Have fun programming with FINAL CUT..._

**Comment by euroboros** [comment]
Dear Markus,
Many thanks for your reply !
In fact, yesterday I located the source of error! So my solution is to add the following in to any of my code just after `include <final/final.h>`,
```c++
#undef device_type
#undef tab
#undef newline
#undef columns
#undef buttons
#undef lines
#undef key_next
#undef key_end
```
BTW, since my code and deal.II mainly works for parallel numerical simulation, how can i make final cut coexist with MPI together? If I want reuse some of my own code, I have to remove anything relevant with MPI.

Guten Tag,

Zhenyu

**Comment by euroboros** [comment]
I found the above keywords not used by Final Cut, could you also undefine them in next release?

**Comment by gansm** [comment]
Hi Zhenyu, thank you for the feedback.
The reason for this is that FINAL CUT uses the [Termcap library](https://en.wikipedia.org/wiki/Termcap).

```cpp
#include <term.h> // termcap
```

Several hundred keywords (including terminal capabilities) are defined here by the preprocessor.
Unfortunately, we have different termcap implementations:

**Linux:**
```bash
> grep -c "#define" /usr/include/term.h 
535
```

**NetBSD:**
```bash
> grep -c "#define" /usr/include/term.h 
934
```

Maybe it is possible to move the implementation completely into a cpp file.

----

What does the acronym MPI stand for? On Wikipedia I found several meanings for it: https://en.wikipedia.org/wiki/MPI

**Comment by euroboros** [comment]
MPI for Message Passing Interface, it may be the mostly wide used parallel library for numerical simulation.
I isolated it from my finalcut parameter UI. The UI should work as a serial one.

Best regards,

Zhenyu

**Comment by gansm** [comment]
Very interesting, there are so many libraries for special purposes. Debian alone has over 6000 libraries on board. 

Well, I was successful in hiding the macros of the termcap library to the outside (73faadd). Many thanks for this hint, which makes FINAL CUT even better usable now.

**Comment by euroboros** [comment]
You're welcome, Markus,
May I suggest more for your TODO, such as
    Horizontal / Vertical layout
    TextEdit other than LineEdit?

Another thing is: there may not be adequate assertions in Final Cut. It only throw segfault when something wrong occurred.
For example, last week I tried to call `addColumn` three times in a tree view, but when I insert items, I only gave them with only two values. No more information but segfault popped up at run time. It took long valuable time for locating the error, esp. for a careless programmer like me .

Many thanks!

Zhenyu

**Comment by euroboros** [comment]
You're welcome, Markus,
May I suggest more for your TODO, such as
    Horizontal / Vertical layout
    TextEdit other than LineEdit?

Another thing is: there may not be adequate assertions in Final Cut. It only throw segfault when something wrong occurred.
For example, last week I tried to call `addColumn` three times in a tree view, but when I insert items, I only gave them with only two values. No more information but segfault popped up at run time. It took long valuable time for locating the error, esp. for a careless programmer like me .

Many thanks!

Zhenyu

**Comment by gansm** [comment]
Hi Zhenyu, great thanks for your input.
A FTextEdit widget as text editor is definitely planned for the future.
For the layout I plan to develop the FGrid widget class. There is already a rough implementation concept for this:

```cpp
FGrid grid(FDialog, FSize);
grid.attach (FButton, row, col);
```

```
__________________________________
| - |         FDialog             ▄
┌────────────────────────────────┐█
│▒▒▒▒▒▒▒▒▄                       │█  WidgetAlignment::start
│ ▀▀▀▀▀▀▀▀                       │█
│ - - - - - - - - - - - - - - - -│█
│           ▒▒▒▒▒▒▒▒▄            │█  WidgetAlignment::center
│            ▀▀▀▀▀▀▀▀            │█
│ - - - - - - - - - - - - - - - -│█
│                      ▒▒▒▒▒▒▒▒▄ │█  WidgetAlignment::end
│                       ▀▀▀▀▀▀▀▀ │█
│ - - - - - - - - - - - - - - - -│█
│ ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▄ │█  WidgetAlignment::fill
│  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ │█
└────────────────────────────────┘█
 ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
(dialog with 4 rows, 1 column, and horizontal alignment)
```

```cpp
FButton->setAlignment (WidgetAlignment::start, WidgetAlignment::center);
                      [horizontal alignment]   [vertical alignment]
```

```cpp
enum class WidgetAlignment
{
  fixed,
  start,
  center,
  end,
  fill
};

(fixed means use fixed coordinates)
```

----

Unfortunately I could not reproduce a segfault with a FListView::addColumn() call. I would be very grateful if you could create a separate github issues with a small code example for this.

**Comment by euroboros** [comment]
Dear Markus,
I do need a try for the FGrid widget later.
As for the seg fault, though it happened randomly, I believe it is due to that some members in FListView are uninitialized when I create the object. I will find some time to write a demo code for you. Any way, it is my fault, not yours. I just want to suggest some more assertions to show error information and then reduce the debug time.

I had another question yesterday. I want to add a widget group integrated in the main frame. It should consist of different widgets, such as LineEdit with labels, checkboxes, etc. Initially, I derived such a class based on FWindow, or FDialog. The one from FWindow returned lots of low level memory filling errors in GDB. The other one from FDialog can work, but in a separate window with the unwanted title bar. Could you suggest a better way for this work?

Cheers,

Zhenyu

**Comment by euroboros** [comment]
Another feeling is a new widget should leave the user the freedom to switch the title bar. 
FGrid looks have a FDialog parent with specified sizes. This may not be good to act as a layout. 
In Qt and or TermOx, the layout looks transparent and flexible and they does not work separately from the main frame.
A layout is bound to be an organization of widgets. FGrid seems not.

**Comment by gansm** [comment]
Hi Zhenyu, you can't test the `FGrid` widget (without having a time machine) because it is a planned future widget. It should be able to be a child widget of any widgets. It implements a grid with x columns and y rows, in whose grid cells widgets can be placed. A widget should be automatically aligned within its grid cell.  So a grid cell must have at least the size of its child widget.  A grid cell should also be able to contain another `FGrid` widget as a child widget. This is my current plan for my planned implementation.

For grouping widgets, I would recommend using the `FScrollView` widget with a scroll area no larger than the widget itself. Unless you use `FCheckBox` or `FRadioButton` widgets, then you should use the `FButtonGroup` widget for grouping.

Here is a simple example:

```cpp
#include <final/final.h>

using finalcut::FPoint;
using finalcut::FSize;

class Scrollview final : public finalcut::FScrollView
{
  public:
    explicit Scrollview (finalcut::FWidget* parent = nullptr)
      : finalcut::FScrollView{parent}
    {
      widget1.setGeometry ( FPoint{8, 2}, FSize{20, 1} );
      widget1.setLabelText (L"&Input");
      widget2.setGeometry ( FPoint{2, 4}, FSize{12, 1} );
      widget3.setGeometry ( FPoint{2, 6}, FSize{10, 1} );
      widget4.setGeometry ( FPoint{2, 8}, FSize{10, 1} );
    }

    ~Scrollview()
    { }

    void draw()
    {
      const auto& wc = getColorTheme();
      setColor (wc->label_inactive_fg, wc->dialog_bg);
      clearArea();
      FScrollView::draw();
    }

  private:
    finalcut::FLineEdit widget1{"Widget 1", this};
    finalcut::FButton   widget2{"&Widget 2", this};
    finalcut::FCheckBox widget3{"Wid&get 3", this};
    finalcut::FSwitch   widget4{"Widge&t 4", this};
};


class MainDialog final : public finalcut::FDialog
{
  public:
    explicit MainDialog (finalcut::FWidget* parent = nullptr)
      : finalcut::FDialog{"A simple dialog", parent}
    {
      FDialog::setGeometry (FPoint{22, 3}, FSize{37, 18});
      group_of_widgets.setGeometry(FPoint{3, 2}, FSize{31, 11});
      quit_btn.setGeometry(FPoint{24, 14}, FSize{10, 1});
      quit_btn.addCallback ("clicked", [this] () { close(); } );
    }

    ~MainDialog()
    { }

  private:
    Scrollview group_of_widgets{this};
    finalcut::FButton quit_btn{"&Quit", this};
};


int main (int argc, char* argv[])
{
  finalcut::FApplication app{argc, argv};
  MainDialog mail_dgl{&app};
  finalcut::FWidget::setMainWidget(&mail_dgl);
  mail_dgl.show();
  return app.exec();
}
```

![image](https://user-images.githubusercontent.com/12223838/109726087-63947180-7bb2-11eb-85ec-5e5a08d310e7.png)


I would be very grateful for some assertion suggestions, as I lack a bit of an outside perspective as a FINAL CUT developer. So it's hard for me to see the pitfalls of using FINAL CUT.

Thanks a lot!

Markus

**Comment by euroboros** [comment]
HI, Markus,
I never imagine to do the grouping work with a FScrollView.
You will be notified if it works for me, :). And I am also looking forward to your progress on FGrid and or TextEdit.
Cheers a lot,
Zhenyu

**Comment by euroboros** [comment]
Dear Markus,

The FScrollview works now for grouping widgets in my UI now, and without the unwanted headline.
Many thanks
