### ISSUE TITLE
broken configure script

### ISSUE THREAD

**Issue by okbob** [gansm/finalcut#84]
## Describe the bug

Give a detailed description of what the bug is.

The configure fails
```
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: creating ./config.lt
config.lt: creating libtool
./configure: line 18353: syntax error near unexpected token `[-std=c++11],,'
./configure: line 18353: `AX_CHECK_COMPILE_FLAG([-std=c++11],,'
[pavel@localhost finalcut]$ 
```

## How to reproduce the bug?

try to compile final cut on Fedora Core 34

Explain step-by-step the procedure to reproduce this behavior.

## What behavior did you expect?

Describe what you would expect instead.

## In which environment did the bug occur?
* Which operating system do you use?<br />
    Linux, FreeBSD, NetBSD, OpenBSD, macOS, Cygwin, or Solaris

* Which distribution do you use?

* On which CPU architecture did you test?

* Which compiler in which version did you use?

* Which terminal do you use?

* What does the environment variable $TERM contain?

**Comment by okbob** [comment]
I found an solution - it needs installed `autoconf-archive` package. Without it - an autogen.sh is ok, but configure fails. Please, can be this dependency documented?

**Comment by gansm** [comment]
Hi Pavel, this dependency is mentioned in the FAQs:

&#160;&#160;&#160;&#160;[What do I need to build this library?](https://github.com/gansm/finalcut/blob/main/doc/faq.md#what-do-i-need-to-build-this-library)


I have improved the GNU autoconf-archive check (a3a4e4a), so that it now hopefully works on all systems:

```bash
& autoreconf --install --force
& ./configure --prefix=/usr
[...]
configure: creating ./config.lt
config.lt: creating libtool
configure: error: Macro AX_CXX_COMPILE_STDCXX_11 not found. Please install GNU autoconf-archive
```

**Comment by okbob** [comment]
ne 18. 7. 2021 v 20:58 odesílatel Markus Gans ***@***.***>
napsal:

> Hi Pavel, this dependency is mentioned in the FAQs:
>
>     What do I need to build this library?
> <https://github.com/gansm/finalcut/blob/main/doc/faq.md#what-do-i-need-to-build-this-library>
>
> I have improved the GNU autoconf-archive check (a3a4e4a
> <https://github.com/gansm/finalcut/commit/a3a4e4a43fcb585a0bccfd254f1fd4d8aa31eda5>),
> so that it now hopefully works on all systems:
>
> & autoreconf --install --force
> & ./configure --prefix=/usr
>
> [...]
>
> configure: creating ./config.lt
> config.lt: creating libtool
>
> configure: error: Macro AX_CXX_COMPILE_STDCXX_11 not found. Please install GNU autoconf-archive
>
>
super, thank you very much
