### ISSUE TITLE
How to hide or disable icon in the left corner in FDialog. How to make an exit button in my own FDialog.

### ISSUE THREAD

**Issue by pavelvm5** [gansm/finalcut#89]
Hello, i've two issues.
1) I will use my project with your library in tty, so i dont need to use this left-corner icon. How can i remove it? 
And how to resize this top-label.
![image](https://user-images.githubusercontent.com/56404416/136433656-30161f93-5239-4a1c-a8fc-dd25dcc27fbc.png)
All I need is to use labels and active buttons. Adding back or next buttons i will navigate throw these windows, overlapping or closing old ones. See the example below.
It is very easy to make and configure them by using FDialog.

2) I need to make my own exit-confirmation dialog, cause i need to translate it on different languages. The best idea i have is to create main widget and make an access to it using my exit-button. Am i right?
Can you give a short example, if it isn't so hard.
![image](https://user-images.githubusercontent.com/56404416/136436733-ff650b0a-e22f-430d-83d4-1e0cb397d6a7.png)

P.S. Your library is awesome! Thx for creating it!
P.P.S Sorry for my bad English, I haven't practiced for so long.

**Comment by gansm** [comment]
Thank you very much for your comment. Indeed, hiding the menu buttons is a flexibility that `FDialog` lacked until today. I have added this feature now (8d9bb75).

```cpp
FDialog dialog;
dialog.setTitleBarButtonVisibility();       // Show all title bar buttons
dialog.unsetTitleBarButtonVisibility();     // Hide all title bar buttons

// or 

dialog.setTitlebarButtonVisibility(true);   // Show all title bar buttons
dialog.setTitlebarButtonVisibility(false);  // Hide all title bar buttons
```

For internationalization and localization (i18n and l10n) I plan to use [GNU gettext](https://en.wikipedia.org/wiki/Gettext) in the future. In the meantime you need to build your own translated widget.

Here is a small example program that allows you to create your own confirmation dialog on exit:

```cpp
#include <final/final.h>

using namespace finalcut;

void myQuitConfirmationDialog (FWidget* parent, FCloseEvent* ev)
{
  const FMessageBox::ButtonType ret = \
      FMessageBox::info ( parent, "Exit confirmation dialog"
                        , "Are you sure you want to quit?"
                        , FMessageBox::ButtonType::Yes
                        , FMessageBox::ButtonType::No );

  if ( ret == FMessageBox::ButtonType::Yes )
    ev->accept();
  else
    ev->ignore();
}

class dialogWidget : public FDialog
{
  public:
    explicit dialogWidget (FWidget* parent = nullptr)
      : FDialog{parent}
    {
      // Connect the button signal "clicked" with the callback method
      button.addCallback
      (
        "clicked",
        finalcut::getFApplication(),
        &finalcut::FApplication::cb_exitApp,
        this
      );
    }

  private:
    void initLayout()
    {
      setText ("Main menu");
      setGeometry (FPoint{25, 5}, FSize{20, 11});
      button.setGeometry (FPoint{5, 7}, FSize{10, 1});
      label.setGeometry (FPoint{1, 1}, FSize{getClientWidth(), 5});
      label.setAlignment (Align::Center);
      FDialog::initLayout();
    }

    void onClose (finalcut::FCloseEvent* ev) override
    {
      myQuitConfirmationDialog (this, ev);
    }

    FButton button{"&Exit", this};
    FLabel label{"(1) ...\n\n(2) ...\n\n(3) ...", this};
};

int main (int argc, char* argv[])
{
  FApplication app(argc, argv);
  dialogWidget dialog(&app);
  dialog.unsetTitleBarButtonVisibility();
  FWidget::setMainWidget(&dialog);
  dialog.show();
  return app.exec();
}
```

I hope I was able to help you.

**Comment by 9PashaE6ashu** [comment]
Excuse me, but can you add another one function - make this corner unreachable if it's hidden, or make another one function to make it unreachable.
Cause i still can click on it or ctrl+6.

**Comment by gansm** [comment]
Now, FDialog should behave as desired (81b2c9d).
