### ISSUE TITLE
Compilation problems (minor)

### ISSUE THREAD

**Issue by WarShoe** [gansm/finalcut#9]
I have two minor compilation problems with finalcut

1. "fobject.h" includes "final/emptyfstring.h", but "emptyfstring.h" is not copied by default with "make install" command.
2. In the source code "register" word is used, but:
warning: ISO C++1z does not allow ‘register’ storage class specifier

**Comment by WarShoe** [comment]
the fixes are trivial, but I can provide 'pull' request if you wish.

**Comment by gansm** [comment]
A pull request would be great.

**Comment by gansm** [comment]
Both problems are now fixed.
Thank you very much for your report.
