### ISSUE TITLE
can i see images with finalcut ?

### ISSUE THREAD

**Issue by alavaelian** [gansm/finalcut#94]
hello is posible to watch images in final cut ?.

**Comment by alexmyczko** [comment]
maybe if you also add https://github.com/hpjansson/chafa or https://github.com/cacalabs/libcaca ?

**Comment by alavaelian** [comment]
> maybe if you also add https://github.com/hpjansson/chafa or https://github.com/cacalabs/libcaca ?

more like https://github-wiki-see.page/m/ranger/ranger/wiki/Image-Previews

**Comment by gansm** [comment]
FINAL CUT does not have [Sixel](https://en.wikipedia.org/wiki/Sixel) or [ReGIS](https://en.wikipedia.org/wiki/ReGIS) support. But it should be possible to use a library like [chafa](https://hpjansson.org/chafa/) to display images in a FINAL CUT dialog box.

**Comment by alavaelian** [comment]
> FINAL CUT does not have [Sixel](https://en.wikipedia.org/wiki/Sixel) or [ReGIS](https://en.wikipedia.org/wiki/ReGIS) support. But it should be possible to use a library like [chafa](https://hpjansson.org/chafa/) to display images in a FINAL CUT dialog box.

is planned to add support for this in the future or maybe is pretty imposible ?

**Comment by gansm** [comment]
FINAL CUT is primarily intended to provide an interactive user interface. 

But FINAL CUT provides an abstract terminal control (similar to [ncurses](https://en.wikipedia.org/wiki/Ncurses)). Therefore, the programming is identical for all terminals. This is an excellent base to implement something like this.

For those interested in this, it should be easy to create your own image widget. `FDialog` and `FScrollView` would be helpful here.

**Comment by gansm** [comment]
In the meantime, there is also a viewer for XPM images in the examples.

[https://www.reddit.com/r/linux/comments/st4npl/xpm_viewer_for_terminal/](https://www.reddit.com/r/linux/comments/st4npl/xpm_viewer_for_terminal/)

**Comment by alavaelian** [comment]
is posibble that can i use xpm as icons i mean for the buttons

**Comment by gansm** [comment]
No, because I do not address pixels but only use Unicode characters ("▀", "▄") for their representation. A 16x16 pixel icon covers an area of 16x8 characters in the terminal.
